import type { Metadata } from "next";
import Link from "next/link";
import Portrait from "@/components/Portrait";
import Starburst from "@/components/Starburst";
export const metadata: Metadata = { title: "About", description: "The human behind bytebeard_: curious student, maker, photographer and aspiring game developer." };
export default function AboutPage() {return <main className="page-main about-page"><section className="about-hero paper-section"><div className="page-eyebrow"><span>PERSONAL FILE / 002</span><span>A LITTLE MORE HUMAN</span></div><h1 className="about-bubble">NOT A PRO.<br/><span>NOT PRETENDING.</span></h1><div className="about-stage"><Starburst className="star about-star"/><Portrait/><span className="about-stage-scribble">just building<br/>my own thing ↗</span></div><div className="about-hero-bottom"><span>HELLO, I&apos;M BYTEBEARD_.</span><p>A student who learns by making things, breaks things while learning, and sometimes photographs the sky in between.</p></div></section><section className="about-manifesto red-section"><span className="eyebrow light">A QUICK INTRODUCTION</span><div className="manifesto-row"><h2 className="hand-title light">Half code.<br/>Half chaos.<br/><em>Still curious.</em></h2><div><p>I&apos;m into front-end development, interactive web design and the details that make a site feel alive. Most things I&apos;ve built started as practice. That&apos;s the point.</p><p>Outside code: cinematic photography, anime and games that build entire worlds in your head. Long term, I want to make games of my own.</p><Link href="/work" className="pill-link light-link">SEE WHAT I&apos;VE MADE ↗</Link></div></div><Starburst className="star manifesto-star"/></section><section className="about-now paper-section"><div className="about-now-top"><span className="eyebrow">CURRENTLY, IN NO PARTICULAR ORDER</span><h2>THE THINGS<br/><em>ON MY MIND.</em></h2></div><div className="now-list">{[
  ["01", "THE WEB", "HTML, CSS, JavaScript and the endless temptation to animate one more thing."],
  ["02", "THE CAMERA ROLL", "Clouds. Strange light. Empty streets. Trying to notice what other people pass by."],
  ["03", "GAME WORLDS", "Elden Ring, Sekiro and the bigger ambition: learning how to build worlds of my own."],
  ["04", "THE NEXT EXPERIMENT", "Getting better by building things that are a little harder than the last."],
 ].map(([n, title, desc]) => <div className="now-row" data-reveal key={n}><span>{n}</span><h3>{title}</h3><p>{desc}</p><span>↗</span></div>)}</div></section></main>; }
