import Link from "next/link";
import Portrait from "@/components/Portrait";
import Starburst from "@/components/Starburst";
import ProjectList from "@/components/ProjectList";
import FrameArt from "@/components/FrameArt";
import { frames } from "@/content/frames";
export default function Home() { return <main>
 <section className="hero" aria-labelledby="home-title">
  <div className="hero-prelude"><span>INDEPENDENT WEB EXPERIMENTS<br/>AND OTHER INTERNET THINGS.</span><p>I&apos;M A STUDENT, MAKER & COLLECTOR OF<br/>IDEAS THAT REFUSE TO STAY IDEAS.</p><span className="hero-handle">@BYTEBEARD_ ↗</span></div>
  <div className="hero-stage"><Starburst className="star hero-star-left"/><Starburst className="star hero-star-right"/><h1 className="blob-word" id="home-title" aria-label="Portfolio">{"portfolio".split("").map((letter, i) => <span key={`${letter}-${i}`} aria-hidden="true">{letter}</span>)}</h1><div className="hero-portrait" data-drift><Portrait/></div><div className="hero-scribble" aria-hidden="true">built different?<br/>still building.</div></div>
  <div className="hero-bottom"><span>↓ SCROLL TO EXPLORE</span><span className="hero-role">CREATIVE CODER<br/>VISUAL COLLECTOR<br/>GAME-WORLD DREAMER</span><a href="#overview" className="round-arrow" aria-label="Skip to introduction">↓</a></div>
 </section>
 <section className="overview red-section" id="overview"><div className="overview-top"><div><span className="eyebrow light">01 / THE HUMAN BIT</span><h2 className="hand-title light">Personal<br/><span>overview</span><span className="hand-dot">.</span></h2></div><p data-reveal>Curiosity is the main skill. Code is the medium. Everything else is an excuse to make something interesting.</p></div><Starburst className="overview-star star"/><div className="overview-art" data-drift><span className="overview-number">01</span><img src="/illustrations/desk-collage.svg" alt="Original illustration of a creative desk, laptop, design notes and photos"/></div><div className="overview-bottom"><span>THE PROCESS IS USUALLY MESSY. THAT&apos;S FINE.</span><Link href="/about" className="pill-link light-link">MORE ABOUT ME <span>↗</span></Link></div></section>
 <section className="competencies paper-section"><div className="competencies-number" aria-hidden="true">02</div><Starburst className="competencies-star star"/><div className="competencies-content"><div className="competencies-image"><Portrait/></div><div className="competencies-copy"><span className="eyebrow" data-reveal>02 / CURRENT OBSESSIONS</span><h2 className="hand-title" data-reveal>Things I can&apos;t<br/>stop <em>making</em><span>.</span></h2><p data-reveal>I like making websites feel like something. I collect clouds and strange light on an old camera. And one day, I want to build game worlds people get completely lost in.</p><div className="skill-tags" data-reveal>{["HTML / CSS / JS", "FRONT-END", "INTERACTIONS", "CREATIVE CODING", "PHOTOGRAPHY", "GAME DESIGN (LEARNING)"].map(tag => <span key={tag}>{tag}</span>)}</div><Link className="text-link" href="/about">THE ENTIRE STORY <span>↗</span></Link></div></div></section>
 <section className="selected-work paper-section" id="work"><div className="section-cap"><span className="eyebrow">03 / THINGS I&apos;VE MADE</span><span>NOT AGENCY WORK. REAL EXPERIMENTS.</span></div><div className="work-title" data-reveal><h2>SELECTED<br/><em>WORK</em><span>.</span></h2><div className="work-caption">SOME FINISHED.<br/>SOME STILL GROWING.<br/>ALL PART OF THE PROCESS.</div></div><ProjectList limit={3}/><div className="work-end"><Link href="/work" className="pill-link">VIEW THE FULL ARCHIVE <span>↗</span></Link><Starburst className="star"/></div></section>
 <section className="frames-teaser red-section"><div className="frames-title"><span className="eyebrow light">04 / AWAY FROM THE SCREEN</span><h2 data-reveal>FRAMES,<br/><em>NOT JUST</em><br/>FRAMES.</h2><p>A camera roll full of skies, streets and things nobody else stopped to look at.</p><Link href="/frames" className="pill-link light-link">SEE THE PHOTO WALL <span>↗</span></Link></div><div className="frames-preview"><div className="preview-frame one"><FrameArt frame={frames[0]}/><span>01 / BETWEEN CLOUDS</span></div><div className="preview-frame two"><FrameArt frame={frames[1]}/><span>02 / AFTER THE RAIN</span></div><Starburst className="star frames-teaser-star"/></div></section>
 <section className="last-word paper-section"><span className="eyebrow">05 / STILL CURIOUS?</span><h2 data-reveal>GOOD IDEAS<br/>DON&apos;T NEED<br/><em>PERMISSION.</em></h2><div className="last-bottom"><span>WANT TO BUILD OR JUST TALK ABOUT<br/>THE WEIRD CORNERS OF THE INTERNET?</span><Link className="last-cta" href="/contact">SAY HEY <span>↗</span></Link></div></section>
 </main>; }
